// <auto-generated />
namespace SistemaAtivos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class crudusariou : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(crudusariou));
        
        string IMigrationMetadata.Id
        {
            get { return "202605070104103_crud-usariou"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
